#ifndef __lab03MyFrame__
#define __lab03MyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "lab03_GFK.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/log.h>
#include <wx/colordlg.h>
#include <wx/dcmemory.h>
#include <wx/filedlg.h>
#include <wx/dcbuffer.h>

enum object {
SUN = 0,
BIRD = 1
};

/** Implementing MyFrame */
class lab03MyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void _updateDrawArea( wxUpdateUIEvent& event );
		void _saveOnButtonClick( wxCommandEvent& event );
		void _showBananaOnCheck( wxCommandEvent& event );
		void _changeHandPosition( wxScrollEvent& event );
		void _changeStarColor( wxCommandEvent& event );
		void _updateText( wxCommandEvent& event );
		void _chooseObject( wxCommandEvent& event );
	public:
		/** Constructor */
		lab03MyFrame( wxWindow* parent );
	//// end generated class members
		void Repaint();
	private:

		wxBitmap _MyBitmap;
		wxImage  _MyImage;
		int mid_x, mid_y;
		float _hand_position;
		wxColor _pickedColor;

		bool _banana;
		object _obj;
		wxString _inputText;















};

#endif // __lab03MyFrame__
